name: Docker CI/CD

# 触发条件
on:
  push:
    branches: [ main ]  # 改为 main 分支
  pull_request:
    branches: [ main ]  # 改为 main 分支

# 环境变量
env:
  IMAGE_NAME: ${{ secrets.ALIYUN_REGISTRY }}/waiterlin/vue3-blog-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3  # 更新到 v3

    # 设置 Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # 更新到 v2

    # 登录到阿里云容器镜像服务
    - name: Login to Aliyun Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ALIYUN_REGISTRY }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    # 获取版本号
    - name: Get version
      id: version
      run: echo "VERSION=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

    # 构建并推送 Docker 镜像
    - name: Build and push
      uses: docker/build-push-action@v3  # 更新到 v3
      with:
        context: ./backend  # 指定 Dockerfile 所在目录
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    # 部署到服务器
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # 登录到阿里云容器镜像服务
          echo ${{ secrets.ALIYUN_PASSWORD }} | docker login ${{ secrets.ALIYUN_REGISTRY }} -u ${{ secrets.ALIYUN_USERNAME }} --password-stdin
          
          # 拉取最新镜像
          docker pull ${{ env.IMAGE_NAME }}:latest
          
          # 停止并删除旧容器
          docker stop vue3-blog-backend || true
          docker rm vue3-blog-backend || true
          
          # 运行新容器
          docker run -d \
            --name vue3-blog-backend \
            -p 3000:3000 \
            --restart always \
            ${{ env.IMAGE_NAME }}:latest
          
          # 清理未使用的镜像
          docker image prune -f

    # 部署结果通知
    - name: Notification
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const { status, conclusion } = context.job
          const message = `部署${conclusion === 'success' ? '成功' : '失败'}: ${context.repo.owner}/${context.repo.repo}`
          console.log(message) 
